import type { Book, BookReview, BookUpload, DashboardStats, Favorite, ForumPost, ForumReply, Loan, Notification, QRCheckEvent, Reservation, StudyRoom, User } from "./types"

export const mockUser: User = {
  id: "usr-001",
  nombre: "Carlos Mendoza",
  email: "carlos.mendoza@tecmm.edu.mx",
  rol: "estudiante",
  avatar: "",
  reputacion: 4.8,
  prestamosActivos: 3,
  fechaRegistro: "2024-08-15",
}

export const mockUsers: User[] = [
  mockUser,
  {
    id: "usr-002",
    nombre: "Maria Garcia",
    email: "maria.garcia@tecmm.edu.mx",
    rol: "docente",
    avatar: "",
    reputacion: 4.9,
    prestamosActivos: 1,
    fechaRegistro: "2023-01-10",
  },
  {
    id: "usr-003",
    nombre: "Admin Sistema",
    email: "admin@tecmm.edu.mx",
    rol: "admin",
    avatar: "",
    reputacion: 5.0,
    prestamosActivos: 0,
    fechaRegistro: "2022-06-01",
  },
]

export const mockBooks: Book[] = [
  {
    id: "lib-001",
    titulo: "Introduccion a los Algoritmos",
    autor: "Thomas H. Cormen",
    isbn: "978-0-262-03384-8",
    categoria: "Informatica",
    descripcion: "Una guia completa sobre algoritmos y estructuras de datos, ideal para estudiantes de ingenieria en sistemas computacionales. Cubre desde los fundamentos hasta tecnicas avanzadas.",
    portada: "",
    formato: "fisico",
    disponible: true,
    activo: true,
    calificacion: 4.7,
    totalResenas: 128,
    idioma: "Espanol",
    paginas: 1312,
    editorial: "MIT Press",
    anioPublicacion: 2022,
    tags: ["algoritmos", "programacion", "estructuras de datos"],
  },
  {
    id: "lib-002",
    titulo: "Calculo de una Variable",
    autor: "James Stewart",
    isbn: "978-607-522-911-2",
    categoria: "Matematicas",
    descripcion: "Texto clasico de calculo diferencial e integral con aplicaciones y ejemplos resueltos para estudiantes universitarios.",
    portada: "",
    formato: "fisico",
    disponible: true,
    activo: true,
    calificacion: 4.5,
    totalResenas: 95,
    idioma: "Espanol",
    paginas: 896,
    editorial: "Cengage Learning",
    anioPublicacion: 2021,
    tags: ["calculo", "matematicas", "ingenieria"],
  },
  {
    id: "lib-003",
    titulo: "Fisica Universitaria",
    autor: "Sears & Zemansky",
    isbn: "978-607-32-5635-1",
    categoria: "Fisica",
    descripcion: "Referencia fundamental para cursos de fisica universitaria, con problemas resueltos y aplicaciones practicas.",
    portada: "",
    formato: "fisico",
    disponible: false,
    activo: true,
    calificacion: 4.3,
    totalResenas: 72,
    idioma: "Espanol",
    paginas: 1040,
    editorial: "Pearson",
    anioPublicacion: 2020,
    tags: ["fisica", "mecanica", "electromagnetismo"],
  },
  {
    id: "lib-004",
    titulo: "Ingenieria de Software",
    autor: "Ian Sommerville",
    isbn: "978-607-32-2536-4",
    categoria: "Informatica",
    descripcion: "Texto integral sobre procesos, metodos y herramientas de ingenieria de software. Incluye metodologias agiles y DevOps.",
    portada: "",
    formato: "fisico",
    disponible: true,
    activo: true,
    calificacion: 4.6,
    totalResenas: 84,
    idioma: "Espanol",
    paginas: 768,
    editorial: "Pearson",
    anioPublicacion: 2023,
    tags: ["software", "desarrollo", "agile"],
  },
  {
    id: "lib-005",
    titulo: "Base de Datos: Diseno e Implementacion",
    autor: "Abraham Silberschatz",
    isbn: "978-0-07-352332-3",
    categoria: "Informatica",
    descripcion: "Texto fundamental sobre sistemas de bases de datos, modelo relacional, SQL y diseno de esquemas.",
    portada: "",
    formato: "fisico",
    disponible: true,
    activo: true,
    calificacion: 4.4,
    totalResenas: 67,
    idioma: "Espanol",
    paginas: 672,
    editorial: "McGraw-Hill",
    anioPublicacion: 2021,
    tags: ["bases de datos", "SQL", "diseno"],
  },
  {
    id: "lib-006",
    titulo: "Quimica Organica",
    autor: "John McMurry",
    isbn: "978-607-522-489-6",
    categoria: "Quimica",
    descripcion: "Un enfoque biologico de la quimica organica con aplicaciones y mecanismos de reaccion detallados.",
    portada: "",
    formato: "fisico",
    disponible: true,
    activo: true,
    calificacion: 4.2,
    totalResenas: 45,
    idioma: "Espanol",
    paginas: 1104,
    editorial: "Cengage Learning",
    anioPublicacion: 2020,
    tags: ["quimica", "organica", "biologia"],
  },
  {
    id: "lib-007",
    titulo: "Redes de Computadoras",
    autor: "Andrew S. Tanenbaum",
    isbn: "978-607-32-4270-5",
    categoria: "Informatica",
    descripcion: "Referencia completa sobre arquitecturas de red, protocolos y aplicaciones. Desde capa fisica hasta capa de aplicacion.",
    portada: "",
    formato: "fisico",
    disponible: true,
    activo: true,
    calificacion: 4.5,
    totalResenas: 56,
    idioma: "Espanol",
    paginas: 816,
    editorial: "Pearson",
    anioPublicacion: 2022,
    tags: ["redes", "protocolos", "internet"],
  },
  {
    id: "lib-008",
    titulo: "Inteligencia Artificial: Un Enfoque Moderno",
    autor: "Stuart Russell & Peter Norvig",
    isbn: "978-0-13-604259-4",
    categoria: "Informatica",
    descripcion: "El libro de referencia en IA que cubre busqueda, aprendizaje automatico, procesamiento de lenguaje natural y robotica.",
    portada: "",
    formato: "fisico",
    disponible: true,
    activo: true,
    calificacion: 4.8,
    totalResenas: 142,
    idioma: "Espanol",
    paginas: 1132,
    editorial: "Pearson",
    anioPublicacion: 2023,
    tags: ["inteligencia artificial", "machine learning", "IA"],
  },
]

export const mockLoans: Loan[] = [
  {
    id: "pres-001",
    libroId: "lib-001",
    libro: mockBooks[0],
    usuarioId: "usr-001",
    tipo: "fisico",
    fechaPrestamo: "2026-01-15",
    fechaDevolucion: "2026-02-15",
    estado: "activo",
  },
  {
    id: "pres-002",
    libroId: "lib-004",
    libro: mockBooks[3],
    usuarioId: "usr-001",
    tipo: "fisico",
    fechaPrestamo: "2026-01-20",
    fechaDevolucion: "2026-02-20",
    estado: "activo",
  },
  {
    id: "pres-003",
    libroId: "lib-005",
    libro: mockBooks[4],
    usuarioId: "usr-001",
    tipo: "fisico",
    fechaPrestamo: "2025-12-01",
    fechaDevolucion: "2025-12-31",
    estado: "devuelto",
  },
]

export const mockStudyRooms: StudyRoom[] = [
  {
    id: "sala-001",
    nombre: "Sala de Innovacion A1",
    ubicacion: "Edificio Central, Piso 2",
    capacidad: 8,
    equipamiento: ["Proyector", "Pizarron digital", "Wi-Fi", "Aire acondicionado"],
    imagen: "",
    disponible: true,
    horario: "7:00 - 21:00",
    tipo: "grupal",
    coordenadas: { lat: 20.6597, lng: -103.3496 },
  },
  {
    id: "sala-002",
    nombre: "Cubiculos de Estudio B3",
    ubicacion: "Biblioteca Central, Piso 1",
    capacidad: 2,
    equipamiento: ["Escritorio", "Lampara", "Wi-Fi", "Contactos electricos"],
    imagen: "",
    disponible: true,
    horario: "7:00 - 22:00",
    tipo: "individual",
    coordenadas: { lat: 20.6603, lng: -103.3501 },
  },
  {
    id: "sala-003",
    nombre: "Sala Silenciosa C2",
    ubicacion: "Biblioteca Central, Piso 3",
    capacidad: 20,
    equipamiento: ["Escritorios individuales", "Wi-Fi", "Aire acondicionado", "Iluminacion LED"],
    imagen: "",
    disponible: false,
    horario: "8:00 - 20:00",
    tipo: "silenciosa",
    coordenadas: { lat: 20.6603, lng: -103.3501 },
  },
  {
    id: "sala-004",
    nombre: "Laboratorio Multimedia D1",
    ubicacion: "Edificio TIC, Piso 1",
    capacidad: 12,
    equipamiento: ["Computadoras", "Proyector 4K", "Pantalla verde", "Microfono"],
    imagen: "",
    disponible: true,
    horario: "9:00 - 18:00",
    tipo: "grupal",
    coordenadas: { lat: 20.6612, lng: -103.3488 },
  },
]

export const mockReservations: Reservation[] = [
  {
    id: "res-001",
    salaId: "sala-001",
    sala: mockStudyRooms[0],
    usuarioId: "usr-001",
    fecha: "2026-03-02",
    horaInicio: "10:00",
    horaFin: "12:00",
    estado: "confirmada",
    codigoQR: "QR-RES001-SALA001-20260302",
  },
  {
    id: "res-002",
    salaId: "sala-002",
    sala: mockStudyRooms[1],
    usuarioId: "usr-001",
    fecha: "2026-03-03",
    horaInicio: "14:00",
    horaFin: "16:00",
    estado: "confirmada",
    codigoQR: "QR-RES002-SALA002-20260303",
  },
  {
    id: "res-003",
    salaId: "sala-004",
    sala: mockStudyRooms[3],
    usuarioId: "usr-001",
    fecha: "2026-02-28",
    horaInicio: "09:00",
    horaFin: "11:00",
    estado: "completada",
    codigoQR: "QR-RES003-SALA004-20260228",
    checkIn: "08:58",
    checkOut: "10:55",
  },
]

export const mockForumPosts: ForumPost[] = [
  {
    id: "post-001",
    titulo: "Recomendaciones de libros para Estructuras de Datos",
    contenido: "Hola companeros, estoy buscando libros complementarios para el curso de Estructuras de Datos. Ya tengo el de Cormen pero quisiera algo mas practico con ejemplos en Java o Python. Alguna sugerencia?",
    autor: mockUsers[0],
    fecha: "2026-02-10",
    categoria: "Recomendaciones",
    respuestas: 5,
    likes: 12,
    tags: ["libros", "estructuras de datos", "programacion"],
  },
  {
    id: "post-002",
    titulo: "Grupo de estudio para Calculo Integral",
    contenido: "Estoy organizando un grupo de estudio para preparar el examen de calculo integral. Nos reuniriamos en la Sala A1 los martes y jueves de 4 a 6 PM. Quien se apunta?",
    autor: mockUsers[1],
    fecha: "2026-02-08",
    categoria: "Grupos de Estudio",
    respuestas: 8,
    likes: 24,
    tags: ["grupo de estudio", "calculo", "matematicas"],
  },
  {
    id: "post-003",
    titulo: "Problema con prestamo de 'Ingenieria de Software'",
    contenido: "Solicite el prestamo de 'Ingenieria de Software' pero el sistema me marca el ejemplar como no disponible aunque lo vi en el estante. Alguien sabe si hay otro ejemplar o cuando se libera?",
    autor: mockUsers[0],
    fecha: "2026-02-05",
    categoria: "Soporte Tecnico",
    respuestas: 3,
    likes: 2,
    tags: ["soporte", "prestamos", "disponibilidad"],
  },
  {
    id: "post-004",
    titulo: "Nueva coleccion de libros de IA disponible",
    contenido: "Me alegra informarles que hemos anadido 15 nuevos titulos sobre Inteligencia Artificial y Machine Learning al catalogo. Incluye el ultimo de Russell & Norvig actualizado a 2023.",
    autor: mockUsers[1],
    fecha: "2026-02-01",
    categoria: "Anuncios",
    respuestas: 12,
    likes: 45,
    tags: ["anuncio", "IA", "nuevos libros"],
  },
]

export const mockForumReplies: ForumReply[] = [
  {
    id: "reply-001",
    postId: "post-001",
    contenido: "Te recomiendo 'Data Structures and Algorithms in Python' de Goodrich. Es muy didactico y tiene buenos ejemplos.",
    autor: mockUsers[1],
    fecha: "2026-02-10",
    likes: 5,
  },
  {
    id: "reply-002",
    postId: "post-001",
    contenido: "El de Sedgewick en Java tambien es excelente. Lo encontre aqui en la biblioteca.",
    autor: mockUsers[0],
    fecha: "2026-02-11",
    likes: 3,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    mensaje: "Tu prestamo de 'Introduccion a los Algoritmos' vence en 3 dias.",
    tipo: "prestamo",
    leida: false,
    fecha: "2026-02-12",
  },
  {
    id: "notif-002",
    mensaje: "Tu reserva de la Sala A1 ha sido confirmada para el 16 de febrero.",
    tipo: "reserva",
    leida: false,
    fecha: "2026-02-11",
  },
  {
    id: "notif-003",
    mensaje: "Nuevo comentario en tu publicacion 'Recomendaciones de libros'.",
    tipo: "comunidad",
    leida: true,
    fecha: "2026-02-10",
  },
  {
    id: "notif-004",
    mensaje: "Se ha actualizado el catalogo con 15 nuevos libros de IA.",
    tipo: "sistema",
    leida: true,
    fecha: "2026-02-01",
  },
]

export const mockDashboardStats: DashboardStats = {
  totalLibros: 2450,
  prestamosActivos: 387,
  salasDisponibles: 12,
  usuariosActivos: 1823,
  librosPopulares: mockBooks.slice(0, 4),
  actividadReciente: [
    { fecha: "Lun", prestamos: 45, devoluciones: 32 },
    { fecha: "Mar", prestamos: 52, devoluciones: 41 },
    { fecha: "Mie", prestamos: 38, devoluciones: 55 },
    { fecha: "Jue", prestamos: 65, devoluciones: 43 },
    { fecha: "Vie", prestamos: 48, devoluciones: 57 },
    { fecha: "Sab", prestamos: 22, devoluciones: 18 },
    { fecha: "Dom", prestamos: 12, devoluciones: 8 },
  ],
}

// ============================================
// MOCK REVIEWS
// ============================================

export const mockReviews: BookReview[] = [
  {
    id: "rev-001",
    libroId: "lib-001",
    usuarioId: "usr-002",
    usuario: mockUsers[1],
    titulo: "Introduccion a los Algoritmos",
    calificacion: 5,
    comentario: "Excelente libro, muy completo para entender algoritmos desde cero. Lo recomiendo ampliamente para cualquier estudiante de sistemas.",
    fecha: "2026-01-20",
  },
  {
    id: "rev-002",
    libroId: "lib-001",
    usuarioId: "usr-001",
    usuario: mockUsers[0],
    titulo: "Introduccion a los Algoritmos",
    calificacion: 4,
    comentario: "Muy bueno aunque algunos capitulos son densos. Los ejemplos ayudan mucho a entender los conceptos.",
    fecha: "2026-01-25",
  },
  {
    id: "rev-003",
    libroId: "lib-004",
    usuarioId: "usr-001",
    usuario: mockUsers[0],
    titulo: "Ingenieria de Software",
    calificacion: 5,
    comentario: "El mejor libro de ingenieria de software que he leido. Explica muy bien las metodologias agiles.",
    fecha: "2026-02-01",
  },
  {
    id: "rev-004",
    libroId: "lib-008",
    usuarioId: "usr-002",
    usuario: mockUsers[1],
    titulo: "Inteligencia Artificial: Un Enfoque Moderno",
    calificacion: 5,
    comentario: "Referencia obligatoria para cualquier curso de IA. Muy bien estructurado y actualizado.",
    fecha: "2026-02-05",
  },
]

// ============================================
// MOCK FAVORITES
// ============================================

export const mockFavorites: Favorite[] = [
  {
    id: "fav-001",
    libroId: "lib-001",
    libro: mockBooks[0],
    usuarioId: "usr-001",
    fechaAgregado: "2026-01-16",
  },
  {
    id: "fav-002",
    libroId: "lib-008",
    libro: mockBooks[7],
    usuarioId: "usr-001",
    fechaAgregado: "2026-02-03",
  },
  {
    id: "fav-003",
    libroId: "lib-004",
    libro: mockBooks[3],
    usuarioId: "usr-001",
    fechaAgregado: "2026-01-22",
  },
]

// ============================================
// MOCK QR CHECK EVENTS
// ============================================

export const mockQRChecks: QRCheckEvent[] = [
  {
    id: "qr-001",
    reservaId: "res-003",
    tipo: "check-in",
    codigoQR: "QR-RES003-SALA004-20260228",
    fecha: "2026-02-28",
    hora: "08:58",
    validado: true,
  },
  {
    id: "qr-002",
    reservaId: "res-003",
    tipo: "check-out",
    codigoQR: "QR-RES003-SALA004-20260228",
    fecha: "2026-02-28",
    hora: "10:55",
    validado: true,
  },
]

// ============================================
// MOCK BOOK UPLOADS
// ============================================

export const mockBookUploads: BookUpload[] = [
  {
    id: "upload-001",
    titulo: "Clean Code",
    autor: "Robert C. Martin",
    isbn: "978-0-13-235088-4",
    categoria: "Informatica",
    descripcion: "Guia de buenas practicas de programacion. Cubre principios de codigo limpio, refactorizacion y desarrollo agil.",
    formato: "fisico",
    idioma: "Espanol",
    paginas: 464,
    editorial: "Prentice Hall",
    anioPublicacion: 2008,
    tags: ["programacion", "buenas practicas", "refactorizacion"],
    archivoNombre: "clean-code-portada.jpg",
    archivoTamano: 524288,
    archivoTipo: "image/jpeg",
    subidoPor: mockUsers[0],
    estado: "pendiente",
    fechaSubida: "2026-02-10",
  },
  {
    id: "upload-002",
    titulo: "Design Patterns",
    autor: "Gang of Four",
    isbn: "978-0-201-63361-0",
    categoria: "Informatica",
    descripcion: "Patrones de diseno de software orientado a objetos reutilizables. Referencia clasica de arquitectura de software.",
    formato: "fisico",
    idioma: "Espanol",
    paginas: 395,
    editorial: "Addison-Wesley",
    anioPublicacion: 1994,
    tags: ["patrones", "diseno", "arquitectura"],
    archivoNombre: "design-patterns-portada.jpg",
    archivoTamano: 491520,
    archivoTipo: "image/jpeg",
    subidoPor: mockUsers[1],
    estado: "aprobado",
    fechaSubida: "2026-02-08",
  },
  {
    id: "upload-003",
    titulo: "Algebra Lineal y sus Aplicaciones",
    autor: "David C. Lay",
    isbn: "978-607-32-3820-5",
    categoria: "Matematicas",
    descripcion: "Texto introductorio de algebra lineal con enfoque en aplicaciones practicas para ingenieria.",
    formato: "fisico",
    idioma: "Espanol",
    paginas: 576,
    editorial: "Pearson",
    anioPublicacion: 2021,
    tags: ["algebra", "matematicas", "ingenieria"],
    archivoNombre: "algebra-lineal-portada.jpg",
    archivoTamano: 614400,
    archivoTipo: "image/jpeg",
    subidoPor: mockUsers[0],
    estado: "rechazado",
    fechaSubida: "2026-02-05",
  },
]
